# Generated by Django 4.2.5 on 2023-09-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_username_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='telegram username'),
        ),
    ]
