# Generated by Django 4.2.7 on 2023-11-28 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('house_number', models.CharField(max_length=20, verbose_name='house number')),
            ],
            options={
                'verbose_name': 'Counterparty',
                'verbose_name_plural': 'Counterpartys',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('model', models.CharField(max_length=100, verbose_name='product model')),
                ('release_date', models.DateField(verbose_name='product release date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='node name')),
                ('node_type', models.IntegerField(choices=[(0, 'Factories'), (1, 'Retail Networks'), (2, 'Individual Entrepreneurs')], verbose_name='node type')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='debt node-to-node')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_link', to='base.counterparty', verbose_name='contacts')),
                ('products', models.ManyToManyField(to='base.product', verbose_name='products')),
                ('supplier_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplink', to='base.networknode')),
            ],
            options={
                'verbose_name': 'node',
                'verbose_name_plural': 'nodes',
                'ordering': ['pk'],
            },
        ),
    ]
