# Generated by Django 4.2.7 on 2023-11-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_counterparty_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networknode',
            old_name='retail_network',
            new_name='retail_network_link',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='factory',
        ),
        migrations.AddField(
            model_name='networknode',
            name='factory_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factorylink', to='base.networknode'),
        ),
        migrations.AlterField(
            model_name='networknode',
            name='contacts',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_link', to='base.counterparty', verbose_name='contacts'),
        ),
    ]
